# BeginneRs {#beginners}

> Working with data is a core skill for researchers, and increasingly important
> in all professional careers.

> There are many tools for manpulating, visualising and analysing data. R is
> powerful, open-source tool which has gained wide acceptance among researchers
> and in industry, and expertise with R is highly sought after by employers.

> In this course we'll learn R as we go, building a little at a time. This and
> the next session covers the basics (things you would learn as part of an
> undergraduate statistics course at Plymouth). If some of this is familiar,
> there will be extension exercises to enhance your knowledge.

```{r, echo=F, include=F}
knitr::opts_chunk$set(echo = TRUE, collapse=TRUE, cache=TRUE, comment=NA, message=FALSE)
library(tidyverse)
library(webex)
theme_set(theme_minimal())
```

## Session 1

This session will introduce R and RStudio.

## Session 2

This session will develop some addition basic skills in loading and viewing
data.

<!-- add from Andy -->
