# Data handling {#data-handling}

### In brief

> Most time in data analysis is spent 'tidying up' data: getting it into a
> suitable format to get started. Data scientists have a particular definition
> of _tidy_: Tidy datasets are "easy to manipulate, model and visualize, and
> have a specific structure: each variable is a column, each observation is a
> row" [@wickham_tidy_2014].

> It's often not convenient for humans to _enter_ data in a tidy way, so untidy
> data is probably more common than tidy data in the wild. But doing good,
> reproducible science demands that we document each step of our processing in a
> way that others can check or repeat in future. Tools like R make this easier.

## Sesssion 1

We will use the `dplyr` and `data.table` libraries to manipulate and reorganise
data to solve common problems in experimental and applied research.

<!-- recap filter, select then melt, dcast

making tables

 -->

## Session 2

We will use techniques to automate the processing of experimental data. We also
introduce [Rmarkdown](https://rmarkdown.rstudio.com) to communicate and share
our analyses with others, and cover best-practices for data handling and
archive.

<!-- Multiple files

Introduce RMD -->
