# Self-test Quizzes

TODO ADD QUIZ ITEMS FOR ALL SESSIONS

TODO ADD ANSWERS ON SEPARATE PAGES OR USE WEBEX

## Causes and effects {#causes-quiz}

-   Your hypothesis is "sunburn hurts more if you are also hungover". Is this an
    example of mediation or moderation? [Moderation]
-   How do we show correlation in causal diagrams? [a double headed arrow]
-   Is effect modification the same as or different to stratification?
    Same/Different
-   How many variables do we need for mediation to take place: 1/2/3/4?
-   What does it mean if there is no line between two variables in a causal
    diagram?
-   What is another word for omitted variable bias [confounding]
-   What technique can we use to rule out confounding entrirely?
-   Why can't we always use experiments?

## Measurement {#measurement-quiz}

-   When drawing diagrams, observations are drawn as `____` boxes, and latent
    variables are drawn as `____` boxes [square and rounded respectively]

-   Something about diversity/construct validity TODO

-   Something about ambiguity/discriminant validity TODO?

TODO ADD MORE QUESTIONS

## Data {#data-quiz}

TODO

## Regression {#regression-quiz}

TODO

## Multiple regression quiz {#multiple-regression-quiz}

TODO



